<a href="https://colab.research.google.com/github/furkansaygili6/Anemia-Type-Prediction-with-keras/blob/main/Anemia_Type_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from keras.models import Sequential
from keras.layers import Dense
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from keras.utils import to_categorical as to_categorial

In [2]:
df=pd.read_csv("/content/diagnosed_cbc_data_v4 (1).csv")

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1281 entries, 0 to 1280
Data columns (total 15 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   WBC        1281 non-null   float64
 1   LYMp       1281 non-null   float64
 2   NEUTp      1281 non-null   float64
 3   LYMn       1281 non-null   float64
 4   NEUTn      1281 non-null   float64
 5   RBC        1281 non-null   float64
 6   HGB        1281 non-null   float64
 7   HCT        1281 non-null   float64
 8   MCV        1281 non-null   float64
 9   MCH        1281 non-null   float64
 10  MCHC       1281 non-null   float64
 11  PLT        1281 non-null   float64
 12  PDW        1281 non-null   float64
 13  PCT        1281 non-null   float64
 14  Diagnosis  1281 non-null   object 
dtypes: float64(14), object(1)
memory usage: 150.2+ KB


In [4]:
df.head(3)

WBC  LYMp  NEUTp  LYMn  NEUTn   RBC  HGB   HCT   MCV   MCH  MCHC    PLT  \
0  10.0  43.2   50.1   4.3    5.0  2.77  7.3  24.2  87.7  26.3  30.1  189.0   
1  10.0  42.4   52.3   4.2    5.3  2.84  7.3  25.0  88.2  25.7  20.2  180.0   
2   7.2  30.7   60.7   2.2    4.4  3.97  9.0  30.5  77.0  22.6  29.5  148.0   

    PDW   PCT                      Diagnosis  
0  12.5  0.17  Normocytic hypochromic anemia  
1  12.5  0.16  Normocytic hypochromic anemia  
2  14.3  0.14         Iron deficiency anemia

In [5]:
x=df.drop(["Diagnosis"],axis=1)
y=df["Diagnosis"]



In [15]:
m=LabelEncoder()
y=m.fit_transform(df["Diagnosis"])

In [16]:
y

array([5, 5, 1, ..., 0, 0, 0])

In [13]:
m.inverse_transform([0,1,2,3,4,5,6,7,8])

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [17]:
y=to_categorial(y)

In [18]:
y[0]

array([0., 0., 0., 0., 0., 1., 0., 0., 0.])

In [19]:
len(x.columns)

14

In [20]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=67)

In [21]:
model=Sequential()
model.add(Dense(256,activation="relu",input_dim=len(x.columns)))
model.add(Dense(128,activation="relu"))
model.add(Dense(64,activation="relu"))
model.add(Dense(64,activation="relu"))
model.add(Dense(9,activation="softmax"))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [22]:
model.compile(loss="categorical_crossentropy",optimizer="adam",metrics=["accuracy"])
model.fit(x_train,y_train,epochs=256,batch_size=32,validation_split=0.2)

Epoch 1/256
26/26 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - accuracy: 0.2294 - loss: 3.7420 - val_accuracy: 0.2780 - val_loss: 1.7761
Epoch 2/256
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.4210 - loss: 1.6393 - val_accuracy: 0.3220 - val_loss: 1.6805
Epoch 3/256
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3639 - loss: 1.6659 - val_accuracy: 0.2341 - val_loss: 1.8717
Epoch 4/256
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.3995 - loss: 1.5510 - val_accuracy: 0.5317 - val_loss: 1.4525
Epoch 5/256
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5155 - loss: 1.4332 - val_accuracy: 0.4341 - val_loss: 1.6774
Epoch 6/256
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5082 - loss: 1.4097 - val_accuracy: 0.4878 - val_loss: 1.3487
Epoch 7/256
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4893 - loss: 1.4540 - val_accuracy: 0.5561 - val_loss: 1.3031
Epoch 8/256
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5976 - loss: 1.2262 - val_accuracy: 0.4976 - 

In [23]:
df.head(3)

WBC  LYMp  NEUTp  LYMn  NEUTn   RBC  HGB   HCT   MCV   MCH  MCHC    PLT  \
0  10.0  43.2   50.1   4.3    5.0  2.77  7.3  24.2  87.7  26.3  30.1  189.0   
1  10.0  42.4   52.3   4.2    5.3  2.84  7.3  25.0  88.2  25.7  20.2  180.0   
2   7.2  30.7   60.7   2.2    4.4  3.97  9.0  30.5  77.0  22.6  29.5  148.0   

    PDW   PCT  Diagnosis  
0  12.5  0.17          5  
1  12.5  0.16          5  
2  14.3  0.14          1

In [24]:
tahmin=np.array([[9.4,34,58,2.8,4.3,3.3,8.8,32,78,24,26,155,15,0.17]])
sonuc=model.predict(tahmin)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 269ms/step


In [27]:
np.argmax(sonuc)
m.inverse_transform([np.argmax(sonuc)])


array([5])